server:
  port: 8093
  servlet:    context-path: /
spring:  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: tarena
#引入dubbo配置
dubbo:
  scan:
    basePackages: com.jt
  application:
    name: provider-user   #定义服务的名称
  registry:
    address: zookeeper://192.168.10.128:2181?backup=192.168.10.128:2182,192.168.10.128:2183
  protocol:
    name: dubbo   #变量名称，一般固定
    port: 20880   #生产者的端口号

#mybatis-plush配置
mybatis-plus:  type-aliases-package: com.jt.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true  
#引入日志信息
logging:
  level: 
    com.jt.mapper: debug 